### ISSUE TITLE
Using api-client for real client application

### ISSUE THREAD

**Issue by heroin-moose** [wireapp/wire-server#193]
Hi,

Is it a good idea to use api-client library for building a real Wire client? AFAICS it is a more or less complete HTTP API so it would save me some typing if I use wire-server as a git submodule. However, it's obviously an internal part of the project so it can be rewritten/eliminated/etc.

**Comment by jschaul** [comment]
Hi @heroin-moose 

We currently use the `api-client` (through the higher-level [`api-bot`](https://github.com/wireapp/wire-server/tree/develop/libs/api-bot) library) as part of our [smoke tests](https://github.com/wireapp/wire-server/tree/develop/tools/api-simulations). As such, it is unlikely to be removed in the future. Please note that it is not entirely complete and not our priority to keep up-to-date (Pull requests are always welcome if you find an API call which isn't implemented). Instead of using a git submodule, you could also refer to wire-server through your `stack.yaml`, e.g. 

```yaml
packages:
- '.'
- location:
    git: https://github.com/wireapp/wire-server.git
    commit: daa88e58e19f933143eeef386baa6e2bb8dadd7a
  subdirs:
  - libs/api-client
  - libs/api-bot
  extra-dep: true
```

Finally, for building a native Wire client, you may, in case you prefer another implementation language to Haskell, potentially also want to look at https://github.com/wireapp/coax (an incomplete Rust implementation - please note the warnings in the README)
