### ISSUE TITLE
Problem built on OSX.

### ISSUE THREAD

**Issue by yihuang** [wireapp/wire-server#241]
In OSX, I need to specify extra flags to build ``HSOpenSSL``:
```
$ stack install HsOpenSSL-0.11.4.12 \ 
 --extra-lib-dirs=/usr/local/opt/openssl/lib \
 --extra-include-dirs=/usr/local/opt/openssl/include
```
Then when I run ``stack build``:
```
HsOpenSSL-0.11.4.12: unregistering (flags changed from ["--extra-include-dirs=/usr/local/opt/openssl/include","--extra-lib-dirs=/usr/local/opt/openssl/lib"] to [])
```

Is there a way to specify extra flags for ``extra-deps`` packages in ``stack.yaml`` ?

**Comment by elverkilde** [comment]
@yihuang you can set these flags in your global stack config, in `~/.stack/config.yaml`.

You will most likely need these options:
```yaml
extra-include-dirs:
- /usr/local/opt/openssl/include
- /usr/local/opt/icu4c/include

extra-lib-dirs:
- /usr/local/opt/openssl/lib
- /usr/local/opt/icu4c/lib
```
